postgresql:
  restart: always
  image: sameersbn/postgresql:9.4-19
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
  restart: always
  build: .
  links:
    - redis:redisio
    - postgresql:postgresql
    - registry:registry
  ports:
    - "10080:80"
    - "10022:22"
    - 5000
  environment:
    - DEBUG=false
    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

    - OAUTH_GITHUB_API_KEY=client-id
    - OAUTH_GITHUB_APP_SECRET=app-secret
    - OAUTH_GITHUB_SCOPE=user:email
    - OAUTH_GITHUB_URL=https://github.com

    - REGISTRY_ENABLED=true
    - REGISTRY_PORT=5000
    - REGISTRY_API_URL=http://registry:5000/
    - REGISTRY_KEY_PATH=config/registry.key
    - REGISTRY_PATH=/home/git/data/registry
    - REGISTRY_HTTP_SECRET=something-registry-and-gitlab-share
    - REGISTRY_ISSUER=gitlab-issuer
  entrypoint:
    - /bin/bash
    - -x
  command:
    - /sbin/entrypoint.sh
    - app:start
#    - --trace
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
registry:
  image: registry:2
  environment:
    - REGISTRY_HTTP_SECRET=something-registry-and-gitlab-share
    - REGISTRY_LOG_LEVEL=debug
    - REGISTRY_LOG_FORMATTER=text
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry_storage
  volumes:
    - /srv/docker/gitlab/registry:/registry_storage
redis:
  restart: always
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
